### ISSUE TITLE
Use constant nolint formatting

### ISSUE THREAD

**Issue by Bysmyyr** [ashanbrown/nolintlint#1]
Hi, linter looks nice, one question.

Could it force nolint directives to one style. Currently it acceps `//nolint` and `// nolint`(but not more spaces. I think it could be better to only accept one option.

**Comment by ashanbrown** [comment]
Are you able to use golangci-lint?  With that tool, you could control this.  I don't really maintain this linter as a standalone linter anymore, although if you want to make a PR I'd be happy to merge it.  This repo has been integrated into golangci-lint.

**Comment by Bysmyyr** [comment]
Yes I am. Also found that config. Thanks
